


# 에러 처리

에러는 언제나 발생할 수 있다. 발생한 에러에 대해 대처하는 방법은 중요하다.
try/catch 문은 직접적인 에러가 발생했을 떄 (에러 객체?) 는 적절히 대응할 수 있지만,
직접적인 에러가 발생하지 않는 경우도 있다. 

```js
const $button = document.querySelector('button');
// DOM에 버튼 요소가 존재하지 않으면 에러를 발생시키지 않고 null을 반환한다.
```


## 에러 처리의 두가지 방법

- 예외 값들(undefined, null, -1) 등을 단축 평가 (|| &&) 혹은 옵셔널 체이닝 연산자 (?.) 를 이용하는 방법
- try/catch/finally 문을 사용하는 방법
> 일반적으로 두번쨰 경우를 에러 처리라고 한다.



## Error 객체
```js
const error = new Error('invalid');
```

에러 객체는 message프로퍼티와 stack 프로퍼티를 가진다.
|프로퍼티|설명|
|:--:|:--:|
|message|생성자 함수에 인수로 전달한 에러 메세지|
|stack|에러를 발생시킨 콜스택의 호출 정보를 나타내는 문자열 (디버깅용)|


## throw문 
에러 객체를 생성하는 것만으로는 에러가 발생하지 않고 throw 문으로 에러 객체를 던지면 해당 코드에서 에러가 발생하게 된다.


## 에러의 전파

에러는 throw 되지 않으면 콜스택의 아래 방향으로 전파된다. (호출자 방향)

### 주의 
비동기 함수인 setTimeout이나 프로미스 후속 처리 메서드의 콜백 함수에는 호출자가 존재하지 않는다. 

- 태스크 큐나 마이크로태스크 큐에 일시 저장되었다가 콜스택이 비면 푸시되기 때문에 콜 스택의 최하부에 존재하기 떄문

> 태스크 큐와 마이크로태스크 큐에 의 동작 과정에 대해서 잘 공부해둔 것 같다.


